spring:
  profiles:
    active: dev
  application:
    name: LabWebsite
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 10MB

server:
  tomcat:
    max-swallow-size: 30MB

web:
  python:
    env: ${web.python.env}
    commandTA: ${web.python.commandTA}
    input-dir: ${web.python.input-dir}
    result-dir: ${web.python.result-dir}